### ISSUE TITLE
Update for newest OntoGPT extraction template

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/mic-ingest#7]
The newest release of `ontogpt` (1.0.11) has an updated extraction template for MIC extraction.
The full template is here: https://github.com/monarch-initiative/ontogpt/blob/main/src/ontogpt/templates/mic.yaml

It now includes negation, more grounding, retention of a somewhat modified version of the source text for each statement, and fairly consistent reference number extraction.
Relation extraction and grounding could still use some improvement.
I found this one works best at low temperatures (like 0.1), at least with Llama 3.3 70B.

Here's an example of extraction from https://lpi.oregonstate.edu/mic/minerals/chromium , with the named entities list omitted :
```yaml
extracted_object:
  id: ca7c7df0-c09c-4c22-91c4-d414863ce175
  label: Chromium
  nutrient_to_disease_relationships:
    - negated: 'False'
      context: Chromium supplementation may reduce the risk of insulin resistance,
        and therefore possibly may reduce the risk of type 2 diabetes
      references:
        - '35'
        - '43'
      nutrient: CHEBI:28073
      relationship: reduce the risk of
      disease: MONDO:0005148
    - negated: 'False'
      context: Chromium supplementation has been found to reduce concentrations of
        fasting plasma glucose and insulin, and improve HbA1c values in patients with
        type 2 diabetes
      references:
        - '49'
      nutrient: CHEBI:28073
      relationship: reduce concentrations of fasting plasma glucose and insulin, and
        improve HbA1c values
      disease: MONDO:0005148
    - negated: 'False'
      context: Chromium supplementation may be beneficial in the treatment of type
        2 diabetes
      references:
        - '46'
      nutrient: CHEBI:28073
      relationship: beneficial
      disease: MONDO:0005148
    - negated: 'False'
      context: Chromium supplementation may help treat gestational diabetes
      references:
        - '60'
      nutrient: CHEBI:28073
      relationship: may help treat
      disease: MONDO:0005406
    - negated: 'False'
      context: Chromium supplementation may help treat metabolic syndrome
      references:
        - '63'
      nutrient: CHEBI:28073
      relationship: may help treat
      disease: MONDO:0000816
    - negated: 'False'
      context: Chromium supplementation may help treat polycystic ovary syndrome
      references:
        - '66'
        - '67'
        - '68'
        - '69'
      nutrient: CHEBI:28073
      relationship: may help treat
      disease: MONDO:0008487
  nutrient_to_phenotype_relationships:
    - negated: 'False'
      context: Chromium uptake is enhanced in animals when given at the same time
        as vitamin C
      references:
        - '7'
      nutrient: Chromium, Vitamin C
      relationship: enhanced uptake
      phenotype: Chromium uptake
    - negated: 'False'
      context: Chromium supplementation may reduce food craving and intake in overweight
        or obese women
      references:
        - '40'
        - '41'
      nutrient: CHEBI:28073
      relationship: reduce
      phenotype: food craving and intake
    - negated: 'False'
      context: Chromium supplementation may decrease BMI in women with polycystic
        ovary syndrome
      references:
        - '66'
      nutrient: CHEBI:28073
      relationship: decrease
      phenotype: BMI in women with polycystic ovary syndrome
    - negated: 'False'
      context: Chromium supplementation may lower free testosterone concentration
        in women with polycystic ovary syndrome
      references:
        - '66'
      nutrient: CHEBI:28073
      relationship: lower
      phenotype: free testosterone concentration
    - negated: 'False'
      context: Chromium supplementation may decrease fasting serum insulin concentration
        in women with polycystic ovary syndrome
      references:
        - '66'
      nutrient: CHEBI:28073
      relationship: decrease
      phenotype: fasting serum insulin concentration
  nutrient_to_biological_process_relationships:
    - negated: 'False'
      context: Trivalent chromium may potentiate insulin function when provided at
        pharmacological doses
      references:
        - '1'
      nutrient: CHEBI:49544
      relationship: potentiate
      process: insulin function
    - negated: 'False'
      context: Trivalent chromium may be the cofactor for a biologically active molecule
        that could enhance the effects of insulin on target tissues
      references:
        - '10'
      nutrient: CHEBI:49544
      relationship: cofactor
      process: enhance the effects of insulin on target tissues
    - negated: 'False'
      context: Trivalent chromium may inhibit the activity of protein tyrosine phosphatase-1B
        (PTP-1B) and other negative regulators of insulin signaling
      references:
        - '10'
      nutrient: CHEBI:49544
      relationship: inhibit
      process: activity of protein tyrosine phosphatase-1B (PTP-1B) and other negative
        regulators of insulin signaling
    - negated: 'False'
      context: Trivalent chromium may reduce insulin clearance and enhance insulin
        signaling by inhibiting the proteolysis (degradation) of insulin and some
        downstream effectors
      references:
        - '13'
      nutrient: CHEBI:49544
      relationship: reduce, enhance, inhibiting
      process: GO:0009056
    - negated: 'False'
      context: Trivalent chromium may reduce markers of oxidative stress and inflammation
        known to contribute to insulin resistance
      references:
        - '14'
      nutrient: CHEBI:49544
      relationship: reduce
      process: oxidative stress and inflammation
  nutrient_to_health_status_relationships:
    - negated: 'False'
      context: Chromium is associated with healthy cardiovascular system
      references:
        - '9'
        - '31'
      nutrient: CHEBI:28073
      relationship: associated
      anatomy: UBERON:0004535
    - negated: 'False'
      context: Chromium is associated with healthy liver
      references:
        - '13'
      nutrient: CHEBI:28073
      relationship: biolink:associated_with
      anatomy: UBERON:0002107
    - negated: 'False'
      context: Chromium is associated with healthy pancreas
      references:
        - '8'
        - '10'
      nutrient: CHEBI:28073
      relationship: biolink:associated_with
      anatomy: UBERON:0001264
    - negated: 'False'
      context: Chromium is associated with healthy kidneys
      references:
        - '15'
        - '86'
      nutrient: CHEBI:28073
      relationship: biolink:associated_with
      anatomy: UBERON:0002113
  nutrient_to_source_relationships:
    - negated: 'False'
      context: Chromium is a nutrient of whole-grain products
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: whole-grain products
    - negated: 'False'
      context: Chromium is a nutrient of high-bran cereals
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: high-bran cereals
    - negated: 'False'
      context: Chromium is a nutrient of green beans
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: FOODON:00004236
    - negated: 'False'
      context: Chromium is a nutrient of broccoli
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: FOODON:00003405
    - negated: 'False'
      context: Chromium is a nutrient of nuts
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: FOODON:03303171
    - negated: 'False'
      context: Chromium is a nutrient of egg yolk
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: egg yolk
    - negated: 'False'
      context: Chromium is a nutrient of processed meats
      references:
        - '70'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: processed meats
    - negated: 'False'
      context: Chromium is a nutrient of supplements, including chromium chloride,
        chromium nicotinate, chromium picolinate, and high-chromium yeast
      references:
        - '73'
      nutrient: CHEBI:28073
      relationship: biolink:nutrient_of
      source: supplements
  nutrient_to_nutrient_relationships:
    - negated: 'False'
      context: Chromium competes for one of the binding sites on the iron transport
        protein, transferrin
      references:
        - '15'
      nutrient_subject: CHEBI:28073
      relationship: competes
      nutrient_object: CHEBI:18248
    - negated: 'False'
      context: Chromium uptake is enhanced in animals when given at the same time
        as vitamin C
      references:
        - '7'
      nutrient_subject: CHEBI:28073
      relationship: enhanced uptake with
      nutrient_object: CHEBI:176783
    - negated: 'False'
      context: Chromium may interact with calcium carbonate or magnesium hydroxide-containing
        antacids
      references:
        - '7'
      nutrient_subject: CHEBI:28073
      relationship: interact
      nutrient_object: calcium carbonate, magnesium hydroxide
    - negated: 'False'
      context: Chromium may interact with non-steroidal anti-inflammatory drugs, aspirin
        and indomethacin
      references:
        - '7'
      nutrient_subject: CHEBI:28073
      relationship: interact
      nutrient_object: None
```
